<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Error page</title>

    <link rel="stylesheet" href="assets/css/error-page.css">
</head>

<body>

    <div id="notfound">
        <div class="notfound">
            <div class="notfound-404">
                <div></div>
                <h1>404</h1>
            </div>
            <h2>Página não encontrada</h2>
            <p>A página que você está tentando acessar pode ter sido removida, teve
                seu nome alterado ou está temporariamente indisponível
            </p>
            <a href="/">Voltar ao site</a>
        </div>
    </div>

    

</body>

</html>