<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <h2 class="section-title">Veja as útimas vagas adicionadas</h2>
        </div>

        <!-- aqui -->
        <div class="col-xl-12 col-md-12 mb-4">
            <div class="card">
                <div class="two">
                    <div class="d-flex justify-content-end"><img src='assets/img/novo.svg' width='50'></div>
                    <div class="px-3">
                        <div class="round"><img src="assets/uploads/usuario/avatar.png" width="50" /></div>
                    </div>
                    <div class="px-3 pt-3">
                        <h3 class="name">Programador junior</h3>
                        <p class="quote2">Programar rotinas em VBA para Excel</p>
                    </div>

                    <div class="d-flex justify-content-start px-3 align-items-center">
                        <i class="bi bi-list-task"></i>
                        <span class="quote2 pl-2"> Presencial</span>
                    </div>

                    <div class="d-flex justify-content-start px-3 align-items-center">
                        <i class="bi bi-person-add"></i>
                        <span class="quote2 pl-2"> 1 Vaga</span>
                    </div>

                    <div class="d-flex justify-content-between  px-3 align-items-center pb-3">
                        <div class="d-flex justify-content-start align-items-center">
                            <i class="bi bi-calendar3"></i>
                            <span class="quote2 pl-2">22/04/2023 - 2 dias atrás.</span>
                        </div>
                        <div class="d-flex justify-content-end">
                            <a href="#"><button type="button" class="btn btn-primary btn-sm">Ver Vaga</button></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xl-12 col-md-12 mb-4">
            <div class="card">
                <div class="two">
                    <div class="d-flex justify-content-end"><img src='assets/img/novo.svg' width='50'></div>
                    <div class="px-3">
                        <div class="round"><img src="assets/uploads/usuario/avatar.png" width="50" /></div>
                    </div>
                    <div class="px-3 pt-3">
                        <h3 class="name">Programador junior</h3>
                        <p class="quote2">Programar rotinas em VBA para Excel</p>
                    </div>

                    <div class="d-flex justify-content-start px-3 align-items-center">
                        <i class="bi bi-list-task"></i>
                        <span class="quote2 pl-2"> Presencial</span>
                    </div>

                    <div class="d-flex justify-content-start px-3 align-items-center">
                        <i class="bi bi-person-add"></i>
                        <span class="quote2 pl-2"> 1 Vaga</span>
                    </div>

                    <div class="d-flex justify-content-between  px-3 align-items-center pb-3">
                        <div class="d-flex justify-content-start align-items-center">
                            <i class="bi bi-calendar3"></i>
                            <span class="quote2 pl-2">22/04/2023 - 2 dias atrás.</span>
                        </div>
                        <div class="d-flex justify-content-end">
                            <a href="#"><button type="button" class="btn btn-primary btn-sm">Ver Vaga</button></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xl-12 col-md-12 mb-4">
            <div class="card">
                <div class="two">
                    <div class="d-flex justify-content-end"><img src='assets/img/novo.svg' width='50'></div>
                    <div class="px-3">
                        <div class="round"><img src="assets/uploads/usuario/avatar.png" width="50" /></div>
                    </div>
                    <div class="px-3 pt-3">
                        <h3 class="name">Programador junior</h3>
                        <p class="quote2">Programar rotinas em VBA para Excel</p>
                    </div>

                    <div class="d-flex justify-content-start px-3 align-items-center">
                        <i class="bi bi-list-task"></i>
                        <span class="quote2 pl-2"> Presencial</span>
                    </div>

                    <div class="d-flex justify-content-start px-3 align-items-center">
                        <i class="bi bi-person-add"></i>
                        <span class="quote2 pl-2"> 1 Vaga</span>
                    </div>

                    <div class="d-flex justify-content-between  px-3 align-items-center pb-3">
                        <div class="d-flex justify-content-start align-items-center">
                            <i class="bi bi-calendar3"></i>
                            <span class="quote2 pl-2">22/04/2023 - 2 dias atrás.</span>
                        </div>
                        <div class="d-flex justify-content-end">
                            <a href="#"><button type="button" class="btn btn-primary btn-sm">Ver Vaga</button></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- aqui -->

    </div>
</div>