<!DOCTYPE html>
<html lang="en-us">

<head>
	<meta charset="utf-8">
	<title>Meu Emprego</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- ** CSS Plugins Needed for the Project ** -->

	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

	<link rel="stylesheet" href="assets/front/plugins/bootstrap/bootstrap.min.css">
	
	<!-- themefy-icon -->
	<link rel="stylesheet" href="assets/front/plugins/themify-icons/themify-icons.css">
	<!--Favicon-->
	<link rel="shortcut icon" href="assets/favicon.svg" type="image/x-icon" />
	<!-- fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	<!-- Main Stylesheet -->
	<link href="assets/front/style.css" rel="stylesheet" media="screen" />
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<body>
	<!-- header -->
	<header class="shadow-bottom sticky-top bg-white">
		<nav class="navbar navbar-expand-md navbar-light">
			<div class="container">
				<a class="navbar-brand px-2" href="/">Meu emprego</a>
				<button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse text-center" id="navigation">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link text-dark" href="/">Página Inicial</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="/contato">Contato</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="#">Vagas Abertas</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="/login">Entrar</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<!-- /header -->

	<!-- contact -->
	<section class="section">
		<?php $this->content(); ?>
	</section>
	<!-- /contact -->

	<!-- footer -->
	<footer class="section pb-4">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-8 text-md-left text-center">
					<p class="mb-md-0 mb-4">Fábio Faria © 2023 - Desenvolvimento de Sistemas - <a href="https://www.senaimt.ind.br/" target="_blank">Senai</a></p>
				</div>
				<div class="col-md-4 text-md-right text-center">
					<ul class="list-inline">
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-facebook"></i></a></li>
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-twitter-alt"></i></a></li>
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-github"></i></a>
						</li>
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<!-- /footer -->

	<!-- ** JS Plugins Needed for the Project ** -->
	<!-- jquiry -->
	<script src="assets/front/plugins/jquery/jquery-1.12.4.js"></script>
	<!-- Bootstrap JS -->
	<script src="assets/front/plugins/bootstrap/bootstrap.min.js"></script>
	<!-- Main Script -->
	<script src="assets/front/script.js"></script>
</body>

</html>