<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="utf-8">
	<title>Meu Emprego</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- theme meta -->
	<meta name="theme-name" content="template_front1" />

	<!-- ** CSS Plugins necessários para o projeto ** -->

	<!-- Bootstrap -->
	<link rel="stylesheet" href="assets/front/plugins/bootstrap/bootstrap.min.css">
	<!-- themefy-icon -->
	<link rel="stylesheet" href="assets/front/plugins/themify-icons/themify-icons.css">
	<!--Favicon-->
	<link rel="shortcut icon" href="assets/favicon.svg" type="image/x-icon" />
	<!-- fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	<!-- Main Stylesheet -->
	<link href="assets/front/style.css" rel="stylesheet" media="screen" />

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<body>
	<!-- header -->
	<header class="banner overlay bg-cover" data-background="assets/front/images/banner.jpg">
		<nav class="navbar navbar-expand-md navbar-dark">
			<div class="container">
				<a class="navbar-brand px-2" href="/">Meu Emprego</a>
				<button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse text-center mt-4" id="navigation">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link text-dark" href="/">Página Inicial</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="/contato">Contato</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="#">Vagas Abertas</a>
						</li>

						<?php
							use App\Controllers\AuthController;

							if(AuthController::esta_logado()){?>
								<li class="nav-item">
								<a class="nav-link text-dark btn btn-primary" href="/admin">Admin</a>
								</li>
							<?php
							}else{ ?>
								<li class="nav-item">
								<a class="nav-link text-dark btn btn-primary" href="/login">Entrar</a>
								</li>
								<?php
							}
								?>
			


					</ul>
				</div>
			</div>
		</nav>





		<!-- banner -->
		<div class="container section">
			<div class="row">
				<div class="col-lg-8 text-center mx-auto">
					<h1 class="text-white mb-3">Encontre sua vaga de emprego</h1>
					<p class="text-white mb-4">SÃO MAIS DE 12.000 VAGAS</p>
					<div class="position-relative">
						<!-- <form action="">
							<input id="search" class="form-control" placeholder="Não encontrou o que procura? Faça uma busca aqui!"><i class="ti-search search-icon"></i>
							<a type="submit">TEste</a>
						</form> -->
						<form action="">
							<div class="input-group input-group-sm">

								<input type="text" class="form-control" placeholder="Não encontrou o que procura? Faça uma busca aqui!">
								<span class="input-group-append">
									<button type="button" class="btn btn-primary">Buscar!</button>
								</span>

							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<!-- /banner -->
	</header>
	<!-- /header -->

	<!-- topics -->
	<section class="section">
		<?php $this->content(); ?>
	</section>
	<!-- /topics -->

	<!-- call to action -->
	<section>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section px-3 bg-white shadow text-center">
						<h2 class="mb-4">Possui alguma dúvida?</h2>
						<p class="mb-4">Envie sua dúvida para nós, teremos o prazer em responde-lo!</p>
						<a href="/contato" class="btn btn-primary">Contate-nos</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- /call to action -->

	<!-- footer -->
	<footer class="section pb-4">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-8 text-md-left text-center">
					<p class="mb-md-0 mb-4">Copyright © 2023 - Desenvolvimento de Sistemas - <a href="https://www.senaimt.ind.br/" target="_blank">Senai</a></p>
				</div>
				<div class="col-md-4 text-md-right text-center">
					<ul class="list-inline">
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-facebook"></i></a></li>
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-twitter-alt"></i></a></li>
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-github"></i></a>
						</li>
						<li class="list-inline-item"><a class="text-color d-inline-block p-2" href="#"><i class="ti-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<!-- /footer -->

	<!-- ** JS Plugins Needed for the Project ** -->
	<!-- jquiry -->
	<script src="assets/front/plugins/jquery/jquery-1.12.4.js"></script>
	<!-- Bootstrap JS -->
	<script src="assets/front/plugins/bootstrap/bootstrap.min.js"></script>
	<!-- Main Script -->
	<script src="assets/front/script.js"></script>
</body>

</html>